apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: car-service-frontend-deploy
  name: car-service-frontend-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-service-frontend-pod
  template:
    metadata:
      labels:
        app: car-service-frontend-pod
    spec:
      containers:
      - image: mgrsl/car-service-frontend
        name: car-service-frontend
