apiVersion: v1
kind: Service
metadata:
  labels:
    app: car-service-frontend-svc
  name: car-service-frontend-svc
spec:
  ports:
  - nodePort: 32323
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: car-service-frontend-pod
  type: NodePort
